# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger: none

pool:
  vmImage: 'mcr.microsoft.com/pmc/pmc-cli:latest'

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'CSD-Apt-Linux-NonER-TEMP-SANDBOX(b88ca4c8-592e-4ef9-a17e-b4f29727824c)'
    KeyVaultName: 'pmc-dev'
    SecretsFilter: 'devadmin'
    RunAsPreJob: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget -P /tmp/testpackages https://packages.microsoft.com/yumrepos/azurecore-test/Packages/a/auoms-2.3.1-0.universal.x64.rpm
      wget -P /tmp/testpackages https://packages.microsoft.com/yumrepos/azurecore-test/Packages/a/azsec-clamav-2.10.0-146.x86_64.rpm

