# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'pmc-sandbox'
    KeyVaultName: 'adoext'
    SecretsFilter: 'ado-publisher'
    RunAsPreJob: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cat ${0}
      echo "$(ado-publisher)" > /tmp/mycert.pem
      head -n 1 /tmp/mycert.pem
      # echo ${#ado-publisher}
      