# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'pmc-sandbox'
    KeyVaultName: 'adoext'
    SecretsFilter: 'ado-publisher'
    RunAsPreJob: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script:
      #!/bin/bash -e
      export PMC_CLI_MSAL_CERT=$(ado-publisher)
      wget -P /tmp/testpackages https://packages.microsoft.com/yumrepos/azurecore/Packages/a/auoms-2.6.0-5.x86_64.rpm

- task: PublishLinuxPackagesPMC@0
  inputs:
    profile: 'ppe'
    msal_SNIAuth: 'no-msal-sniauth'
    msal_client_ID: 'd7aedd7c-c2c6-4e86-8126-b72066e0e865'
    package_path: '/tmp/testpackages'
    repository: 'ado-test-yum'